thresholds:
  left_arm:
    joint:
      left_arm_0_error: 0.01
      left_arm_1_error: 0.01
      left_arm_2_error: 0.01
      left_arm_3_error: 0.01
      left_arm_4_error: 0.01
      left_arm_5_error: 0.01
      left_arm_6_error: 0.01
    cartesian:
      l_trans_error: 0.02
      l_rot_error: 0.03
  right_arm:
    joint:
      right_arm_0_error: 0.01
      right_arm_1_error: 0.01
      right_arm_2_error: 0.01
      right_arm_3_error: 0.01
      right_arm_4_error: 0.01
      right_arm_5_error: 0.01
      right_arm_6_error: 0.01
    cartesian:
      r_trans_error: 0.02
      r_rot_error: 0.03
goals:
  left_arm:
    joint: [-1.935, 0.989, -1.564, 1.77, 0.46, 0.853, -0.369]
    cartesian: [1.0, 0.1, 1.4, 0.0, 0.7071, 0.0, 0.7071]
  right_arm:
    joint: [0.0, -1.248, 0.877, 1.61, 1.511, 0.435, -1.012]
    cartesian: [0.776, -0.414, 1.031, -0.719, 0.127, -0.165, 0.663]
