thresholds:
  bodypart_moves:
    left_arm: 0.008
    right_arm: 0.008
    torso: 0.001
  motion_old: 0.5
body_controllables:
  right_arm:
    - right_arm_0_joint
    - right_arm_1_joint
    - right_arm_2_joint
    - right_arm_3_joint
    - right_arm_4_joint
    - right_arm_5_joint
    - right_arm_6_joint
  left_arm:
    - left_arm_0_joint
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
  torso: triangle_base_joint
frame_id: base_footprint
l_frame_id: left_gripper_tool_frame
r_frame_id: right_gripper_tool_frame
update_period: 0.05
server_timeout: 2.0
