thresholds:
  bodypart_moves:
    left_arm: 0.03
    right_arm: 0.03
    torso: 0.005
  motion_old: 0.5
body_controllables:
  right_arm:
    - r_elbow_flex_joint velocity
    - r_shoulder_lift_joint velocity
    - r_shoulder_pan_joint velocity
    - r_upper_arm_roll_joint velocity
    - r_wrist_flex_joint velocity
    - r_wrist_roll_joint velocity
  left_arm:
    - l_elbow_flex_joint velocity
    - l_forearm_roll_joint velocity
    - l_shoulder_lift_joint velocity
    - l_shoulder_pan_joint velocity
    - l_upper_arm_roll_joint velocity
    - l_wrist_flex_joint velocity
    - l_wrist_roll_joint velocity
  torso: torso_lift_joint velocity
frame_id: base_link
l_frame_id: l_gripper_tool_frame
r_frame_id: r_gripper_tool_frame
update_period: 0.05
server_timeout: 2.0
